### ISSUE TITLE
self.num_test_samples and self.num_train_samples

### ISSUE THREAD

**Issue by dyh** [akashgokul/294_FinalProj#1]
https://github.com/akashgokul/294_FinalProj/blob/47b0c56c24e754e28312f0fcc57cb03126386a0e/torch/dataset.py#L54-L56

maybe  switch them: [self.num_train_samples:] <--> [:self.num_train_samples]

self.train_img_names = train_and_valid_img_names.iloc[:self.num_train_samples]
self.validation_img_names = train_and_valid_img_names.iloc[self.num_train_samples:]

**Comment by akashgokul** [comment]
Yes, you are correct.

**Comment by akashgokul** [comment]
The colab notebooks, have the most up to date code without this bug. Sorry!
