### ISSUE TITLE
Code is not available for native one-task network which directly outputs semantic segmentation masks of the lane marking

### ISSUE THREAD

**Issue by DrChungAlbert** [akashgokul/294_FinalProj#3]
I can't find the native one-task network code on google drive, could you share again ?

Thanks

**Comment by akashgokul** [comment]
The code for the one-task network is the same as the vanishing point network except the forward function does not return vanishing point prediction (and for brevity the vanishing point weights were not defined in init).

**Comment by DrChungAlbert** [comment]
Thanks for your quickly reply!

When I try to run the Colab link of your Our multi-task CNN , the VPGNet directory seems empty.
I create it by myself, and run Colab code and got the error message below:
FileNotFoundError: [Errno 2] No such file or directory: '/content/gdrive/My Drive/VPGNet/mat_paths.csv
Could you told me where to find files of "VPGNet" in the Colab from yours?

**Comment by akashgokul** [comment]
Unfortunately, I cannot reproduce the error. From what I remember, the mat_paths.csv just contains the paths of the VPGNet data (downloaded from the authors).

**Comment by DrChungAlbert** [comment]
Hi akashgokul 

When I mount the  Colab link of your "multi-task CNN" and missing some files to run it
I have check  VPGNet  github and mat_paths.csv was moved.

Could you supply the correct ver. of VPGNet onto your github or told me the correct branch of VPGNet for running?

With many thanks
Albert
